name: Build CI

on:
    workflow_dispatch:
      inputs:
        type:
          description: 'Build type'
          default: 'npm'
        label:
          description: 'Git Label'
        library:
          description: 'Specific Library'
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
        tags:
          description: 'Build'

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.actor == github.event.repository.owner.login

    strategy:
      matrix:
        #node-version: [8.x, 10.x, 12.x]
        node-version: [13.x]

    steps:
      - name: Build Type
        run: |
          echo ${{ github.event.inputs.type }}
      - name: Repository Dispatch - test
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: thzero/test
          event-type: ${{ github.event.inputs.type }}
          client-payload: '{ "label": "${{ github.event.inputs.label }}" }'
      - name: Repository Dispatch - CLI
        if: github.event.inputs.library == null || github.event.inputs.library == '' || github.event.inputs.library == 'cli'
        uses: peter-evans/repository-dispatch@v1
        with:cli
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: thzero/library_cli
          event-type: ${{ github.event.inputs.type }}
          client-payload: '{ "label": "${{ github.event.inputs.label }}" }'
      # - name: Repository Dispatch - Common
      #   if: github.event.inputs.library == null || github.event.inputs.library == '' || github.event.inputs.library == 'common'
      #   uses: peter-evans/repository-dispatch@v1
      #   with:
      #     token: ${{ secrets.ACCESS_TOKEN }}
      #     repository: thzero/library_common
      #     event-type: ${{ github.event.inputs.type }}
      #     client-payload: '{ "label": "${{ github.event.inputs.label }}" }'
