name: Build CI

on:
    workflow_dispatch:
      inputs:
        type:
          description: 'Build type'
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
        tags:
          description: 'Build'

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.actor == github.event.repository.owner.login

    strategy:
      matrix:
        #node-version: [8.x, 10.x, 12.x]
        node-version: [13.x]

    steps:
      - name: Build Type
        run: |
          echo ${{ github.event.inputs.type }}
      - name: Test Repo
        run: |
          echo curl -X POST https://api.github.com/repos/thzero/test/actions-remote-dispatch-b/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          --data '{"event_type": "${{ github.event.inputs.type }}" }'
