name: Build CI

on:
    workflow_dispatch:
      inputs:
        type:
          description: 'Build type'
          default: 'npm'
        label:
          description: 'Git Label'
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
        tags:
          description: 'Build'

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.actor == github.event.repository.owner.login

    strategy:
      matrix:
        #node-version: [8.x, 10.x, 12.x]
        node-version: [13.x]

    steps:
      - name: Build Type
        run: |
          echo ${{ github.event.inputs.type }}
      - name: Repository Dispatch - CLI
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: thzero/library_cli
          event-type: ${{ github.event.inputs.type }}
          client-payload: '{ "label": "${{ github.event.inputs.label }}" }'
