name: Build Client CI

on:
    repository_dispatch:
      types: [ build_all_client ]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.actor == github.event.repository.owner.login

    strategy:
      matrix:
        #node-version: [8.x, 10.x, 12.x]
        node-version: [13.x]

    steps:
    - name: Event Input
      run: |
        echo event-type: ${{ github.event.action }}
        echo action: ${{ github.event.client_payload.action }}
        echo label: ${{ github.event.client_payload.label }}
        echo library: ${{ github.event.client_payload.library }}
    - name: Repository Dispatch - Client Firebase
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: thzero/library_client_firebase
        event-type: 'build_all'
        client-payload: '{ "action": "${{ github.event.client_payload.action }}", "label": "${{ github.event.client_payload.label }}" }'
    - name: Repository Dispatch - Client Service REST Axios
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: thzero/library_client_service_rest_axios
        event-type: 'build_all'
        client-payload: '{ "action": "${{ github.event.client_payload.action }}", "label": "${{ github.event.client_payload.label }}" }'
    - name: Repository Dispatch - Client Vue
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: thzero/library_client_vue
        event-type: 'build_all'
        client-payload: '{ "action": "${{ github.event.client_payload.action }}", "label": "${{ github.event.client_payload.label }}" }'
    - name: Repository Dispatch - Client Vue3
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: thzero/library_client_vue3
        event-type: 'build_all'
        client-payload: '{ "action": "${{ github.event.client_payload.action }}", "label": "${{ github.event.client_payload.label }}" }'
    - name: Repository Dispatch - Client Svelte
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: thzero/library_client_svelte
        event-type: 'build_all'
        client-payload: '{ "action": "${{ github.event.client_payload.action }}", "label": "${{ github.event.client_payload.label }}" }'
