name: Build Base CI

on:
    repository_dispatch:
      types: [ build_all ]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.actor == github.event.repository.owner.login

    strategy:
      matrix:
        #node-version: [8.x, 10.x, 12.x]
        node-version: [13.x]

    steps:
    - name: Event Input
      run: |
        echo event: ${{ JSON.stringfy(github.event) }}
        echo event-type: ${{ github.event.action }}
        echo action: ${{ github.event.client_payload.action }}
        echo label: ${{ github.event.client_payload.label }}
        echo library: ${{ github.event.client_payload.library }}
    # - name: Repository Dispatch - Client
    #   if: github.event.action == 'build_all'
    #   uses: peter-evans/repository-dispatch@v1
    #   with:
    #     token: ${{ secrets.ACCESS_TOKEN }}
    #     repository: thzero/library_client
    #     event-type: ${{ github.event.action }}
    #     client-payload: '{ "action": "${{ github.event.client_payload.action }}", "label": "${{ github.event.client_payload.label }}" }'
    # - name: Repository Dispatch - Common Service
    #   if: github.event.action == 'build_all'
    #   uses: peter-evans/repository-dispatch@v1
    #   with:
    #     token: ${{ secrets.ACCESS_TOKEN }}
    #     repository: thzero/library_common_service
    #     event-type: ${{ github.event.action }}
    #     client-payload: '{ "action": "${{ github.event.client_payload.action }}", "label": "${{ github.event.client_payload.label }}" }'
