name: Build CI

on:
    repository_dispatch:
    types: [ build_base ]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.actor == github.event.repository.owner.login

    strategy:
      matrix:
        #node-version: [8.x, 10.x, 12.x]
        node-version: [13.x]

    steps:
    - name: Event Input
      run: |
        echo action: ${{ github.event.action }}
        echo label: ${{ github.event.client_payload.label }}
    # - name: Repository Dispatch - Client
    #     uses: peter-evans/repository-dispatch@v1
    #     with:
    #       token: ${{ secrets.ACCESS_TOKEN }}
    #       repository: thzero/library_client
    #       event-type: ${{ github.event.inputs.type }}
    #       client-payload: '{ "label": "${{ github.event.client_payload.label }}", "library": "${{ github.event.inputs.library }}" }'
    # - name: Repository Dispatch - Common Service
    #     uses: peter-evans/repository-dispatch@v1
    #     with:
    #       token: ${{ secrets.ACCESS_TOKEN }}
    #       repository: thzero/library_common_service
    #       event-type: ${{ github.event.inputs.type }}
    #       client-payload: '{ "label": "${{ github.event.client_payload.label }}", "library": "${{ github.event.inputs.library }}" }'
